import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth/session";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { getT } from "@/lib/i18n/server";
import { SignupForm } from "./signup-form";

export const dynamic = "force-dynamic";

/**
 * /signup is the redemption page for an invite link generated by
 * `npm run invite:family`. The token comes from the URL as a query param;
 * if it's missing the page just explains how to get a link.
 *
 * The page itself doesn't validate the token (no DB hit until the form is
 * submitted). That keeps the URL safe to share — visiting without filling
 * the form doesn't consume anything.
 */
export default async function SignupPage({
  searchParams,
}: {
  searchParams?: { token?: string };
}) {
  const t = getT();
  // If the visitor is already logged in elsewhere, send them to their
  // dashboard instead of letting them double-redeem.
  const session = await getSession();
  if (session) {
    redirect(session.role === "PARENT" ? "/parent/dashboard" : "/child/dashboard");
  }

  const token = searchParams?.token?.trim() ?? "";

  return (
    <div className="min-h-screen flex items-center justify-center px-4 py-8 bg-slate-50">
      <div className="w-full max-w-md">
        <Card>
          <CardHeader>
            <CardTitle>{t.signup.title}</CardTitle>
          </CardHeader>
          <CardContent>
            {token.length === 0 ? (
              <EmptyState
                title={t.signup.tokenMissing}
                description={t.signup.description}
              />
            ) : (
              <>
                <p className="text-sm text-slate-600 mb-4">
                  {t.signup.description}
                </p>
                <SignupForm token={token} />
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
